SELECT PHARMACY_NAME FROM DOCTOR NATURAL JOIN HASDOC NATURAL JOIN PHARMACY;
SELECT * FROM DOCTOR NATURAL JOIN CONSULTS NATURAL JOIN PATIENT;

SELECT PATIENT_NAME,PATIENT_EMAIL,PATIENT_ID FROM 
PATIENT NATURAL JOIN CONSULTS NATURAL JOIN DOCTOR
WHERE DOCTOR_ID= 'Doc_00001';

SELECT PHARMACY_ID,PHARMACY_NAME FROM PHARMACY WHERE PHARMACY_NAME= 'Mayer Dua Pharmacy';

SELECT 
PHARMACY_NAME, PHARMACY_EMAIL,
 PHARMACY.PHARMACY_ADDRESS.HOUSE_NO || ' ' ||PHARMACY.PHARMACY_ADDRESS.CITY || ' Road ' || PHARMACY.PHARMACY_ADDRESS.ROAD_NO || ' ' || PHARMACY.PHARMACY_ADDRESS.DISTRICT , 
START_TIME, END_TIME, CONSULT_DAY 
FROM 
SCHEDULE NATURAL JOIN HAS NATURAL JOIN DOCTOR NATURAL JOIN HASDOC NATURAL JOIN PHARMACY WHERE DOCTOR_ID= 'Doc_00001';

SELECT * from schedule NATURAL JOIN HAS NATURAL JOIN DOCTOR NATURAL JOIN HASDOC NATURAL JOIN PHARMACY;



 SELECT 
            PHARMACY_NAME, PHARMACY_EMAIL,
            PHARMACY.PHARMACY_ADDRESS.HOUSE_NO || ' ' ||PHARMACY.PHARMACY_ADDRESS.CITY || ' Road ' || PHARMACY.PHARMACY_ADDRESS.ROAD_NO || ' ' || PHARMACY.PHARMACY_ADDRESS.DISTRICT , 
            START_TIME, END_TIME, CONSULT_DAY 
            FROM 
            SCHEDULE NATURAL JOIN HAS NATURAL JOIN DOCTOR NATURAL JOIN HASDOC NATURAL JOIN PHARMACY WHERE DOCTOR_ID= 'Doc_00001';

SELECT * from doctor;